// Preserved from design snapshot 9e35ba2350cecc709ce01d5552a59d9d59e629fb.
import React,{useEffect,useState}from'react'
import{useNavigate}from'react-router-dom'
import styled from'styled-components'
import{motion}from'framer-motion'
import{format,getDayOfYear}from'date-fns'
import Button from'../components/Button'
import Confetti from'../components/Confetti'
import CountStepper from'../components/CountStepper'
import EmptyState from'../components/EmptyState'
import AppIcon from'../components/AppIcon'
import{useHabits}from'../context/HabitsContext'
import{usePreferences}from'../context/PreferencesContext.jsx'
import{useToast}from'../context/ToastContext'
import{getHabitStreak,getTodayHabits,getTrackingStats,getWeeklyCompletionData,isCompletedOnDate,toDateKey}from'../domain/habitTracking'
import{DEFAULT_HABIT_ICON}from'../domain/iconCatalog'

const Shell=styled(motion.main)`width:min(100%,1220px);margin:0 auto;padding:clamp(20px,4vw,48px) clamp(16px,4vw,52px) 110px;`
const Header=styled.header`display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;gap:16px;padding-bottom:18px;border-bottom:3px solid ${p=>p.theme.colors.borderStrong}`
const Logo=styled.strong`display:inline-block;padding:7px 10px;background:${p=>p.theme.colors.borderStrong};color:${p=>p.theme.colors.background};font-family:${p=>p.theme.typography.displayFamily};font-size:1rem;font-weight:800;letter-spacing:-.04em;text-transform:uppercase;transform:rotate(-2deg)`
const DateStamp=styled.span`font-family:${p=>p.theme.typography.monoFamily};font-size:.68rem;font-weight:600;letter-spacing:.08em;text-transform:uppercase`
const Hero=styled.section`position:relative;display:grid;grid-template-columns:minmax(0,1.25fr) minmax(250px,.75fr);gap:clamp(30px,7vw,80px);align-items:end;padding:clamp(48px,8vw,94px) 0 clamp(38px,6vw,70px);@media(max-width:720px){grid-template-columns:1fr}`
const HeroCopy=styled.div`h1{max-width:8ch;margin:12px 0 20px;font-size:clamp(3.4rem,10vw,8.2rem)}p{max-width:48ch;margin:0;font-weight:500}`
const Badge=styled.span`display:inline-block;padding:6px 9px;background:${p=>p.theme.colors.secondary};color:${p=>p.theme.colors.ink};border:2px solid ${p=>p.theme.colors.borderStrong};font-family:${p=>p.theme.typography.monoFamily};font-size:.61rem;font-weight:600;text-transform:uppercase;transform:rotate(1deg)`
const Score=styled.div`position:relative;min-height:220px;display:flex;flex-direction:column;justify-content:space-between;padding:26px;background:${p=>p.theme.colors.primary};color:${p=>p.theme.colors.onPrimary};border:3px solid ${p=>p.theme.colors.borderStrong};box-shadow:${p=>p.theme.shadows.strong};transform:rotate(2deg);strong{font-family:${p=>p.theme.typography.displayFamily};font-size:clamp(3.3rem,8vw,6.8rem);font-weight:800;line-height:.75;letter-spacing:-.09em}span{font-family:${p=>p.theme.typography.monoFamily};font-size:.65rem;font-weight:600;letter-spacing:.08em;text-transform:uppercase}`
const Sticker=styled.span`position:absolute;right:-8px;bottom:-18px;width:82px;height:82px;display:grid;place-items:center!important;background:${p=>p.theme.colors.secondary};color:${p=>p.theme.colors.ink};border:3px solid ${p=>p.theme.colors.borderStrong};border-radius:50%;font-family:${p=>p.theme.typography.displayFamily}!important;font-size:1rem!important;transform:rotate(12deg)`

const Week=styled.section`display:grid;grid-template-columns:auto repeat(7,minmax(0,1fr));margin-bottom:clamp(48px,7vw,82px);border:3px solid ${p=>p.theme.colors.borderStrong};box-shadow:${p=>p.theme.shadows.medium};@media(max-width:620px){grid-template-columns:repeat(7,minmax(0,1fr))}`
const WeekTitle=styled.div`display:flex;align-items:center;padding:14px;background:${p=>p.theme.colors.borderStrong};color:${p=>p.theme.colors.background};font-family:${p=>p.theme.typography.monoFamily};font-size:.6rem;font-weight:600;text-transform:uppercase;@media(max-width:620px){display:none}`
const Day=styled.div`min-width:0;min-height:82px;display:flex;flex-direction:column;align-items:center;justify-content:space-between;padding:9px 4px;background:${p=>p.$today?p.theme.colors.secondary:p.theme.colors.surface};border-left:2px dashed ${p=>p.theme.colors.borderStrong};font-family:${p=>p.theme.typography.monoFamily};font-size:.54rem;text-transform:uppercase;strong{font-family:${p=>p.theme.typography.displayFamily};font-size:1.35rem}i{width:14px;height:14px;background:${p=>p.$complete?p.theme.colors.primary:'transparent'};border:2px solid ${p=>p.theme.colors.borderStrong};border-radius:50%}`

const Section=styled.section`margin-bottom:clamp(50px,7vw,86px)`
const SectionHeader=styled.div`display:flex;align-items:end;justify-content:space-between;gap:20px;margin-bottom:20px;padding-bottom:14px;border-bottom:3px solid ${p=>p.theme.colors.borderStrong};h2{text-transform:uppercase}`
const Kicker=styled.span`display:block;margin-bottom:7px;font-family:${p=>p.theme.typography.monoFamily};font-size:.62rem;font-weight:600;letter-spacing:.08em;text-transform:uppercase`
const Tickets=styled.div`display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;@media(max-width:680px){grid-template-columns:1fr}`
const Ticket=styled(motion.article)`position:relative;min-width:0;display:grid;grid-template-columns:minmax(0,1fr) 88px;min-height:136px;background:${p=>p.theme.colors.surface};border:3px solid ${p=>p.theme.colors.borderStrong};box-shadow:${p=>p.theme.shadows.medium};cursor:pointer;transform:rotate(${p=>p.$tilt}deg);transition:transform var(--duration-fast),box-shadow var(--duration-fast);&:hover{transform:translate(-3px,-3px) rotate(0);box-shadow:${p=>p.theme.shadows.strong}}@media(max-width:460px){grid-template-columns:minmax(0,1fr)}`
const TicketCopy=styled.div`min-width:0;display:flex;flex-direction:column;justify-content:space-between;gap:18px;padding:20px;h3{overflow:hidden;font-family:${p=>p.theme.typography.displayFamily};font-size:clamp(1.35rem,3vw,2.1rem);font-weight:800;line-height:.95;text-overflow:ellipsis;text-transform:uppercase;white-space:nowrap}`
const TicketMeta=styled.span`display:flex;flex-wrap:wrap;align-items:center;gap:7px;color:${p=>p.theme.colors.text.secondary};font-family:${p=>p.theme.typography.monoFamily};font-size:.57rem;text-transform:uppercase`
const Icon=styled.span`display:inline-flex;color:${p=>p.$color||p.theme.colors.primary}`
const Tear=styled.button`min-height:100%;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;padding:10px;background:${p=>p.$active?p.theme.colors.primary:p.theme.colors.secondary};color:${p=>p.$active?p.theme.colors.onPrimary:p.theme.colors.ink};border-left:3px dashed ${p=>p.theme.colors.borderStrong};font-family:${p=>p.theme.typography.monoFamily};font-size:.58rem;font-weight:600;text-transform:uppercase;transition:background var(--duration-fast),transform var(--duration-fast);&:hover:not(:disabled){background:${p=>p.$active?p.theme.colors.primaryHover:p.theme.colors.surfaceAlt};transform:translateX(-3px)}&:active:not(:disabled){transform:translateX(-7px) rotate(-2deg)}@media(max-width:460px){min-height:72px;flex-direction:row;border-top:3px dashed ${p=>p.theme.colors.borderStrong};border-left:0}}`
const CountTear=styled.div`min-width:0;min-height:100%;display:flex;align-items:center;justify-content:center;padding:8px;border-left:3px dashed ${p=>p.theme.colors.borderStrong};background:${p=>p.theme.colors.secondary};@media(max-width:460px){min-height:72px;border-top:3px dashed ${p=>p.theme.colors.borderStrong};border-left:0}`

const Bulletin=styled.aside`position:relative;display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:20px;margin:0 clamp(0px,8vw,90px) clamp(50px,7vw,86px);padding:22px;background:${p=>p.theme.colors.surface};border:3px solid ${p=>p.theme.colors.borderStrong};box-shadow:${p=>p.theme.shadows.strong};transform:rotate(-1deg);h2{margin-bottom:5px;font-size:1.6rem;text-transform:uppercase}p{margin:0}@media(max-width:620px){grid-template-columns:auto 1fr;margin-inline:0;.bulletin-action{grid-column:2;justify-self:start}}`
const Pin=styled.span`width:46px;height:46px;display:grid;place-items:center;background:${p=>p.theme.colors.secondary};border:2px solid ${p=>p.theme.colors.borderStrong};border-radius:50%;font-family:${p=>p.theme.typography.displayFamily};font-weight:800`
const PathGrid=styled.div`display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;@media(max-width:620px){grid-template-columns:1fr}`
const Path=styled.button`min-height:170px;display:flex;align-items:end;justify-content:space-between;gap:20px;padding:26px;background:${p=>p.$blue?p.theme.colors.primary:p.theme.colors.secondary};color:${p=>p.$blue?p.theme.colors.onPrimary:p.theme.colors.ink};border:3px solid ${p=>p.theme.colors.borderStrong};box-shadow:${p=>p.theme.shadows.medium};text-align:left;transition:transform var(--duration-fast),box-shadow var(--duration-fast);strong{max-width:11ch;color:inherit;font-family:${p=>p.theme.typography.displayFamily};font-size:2rem;line-height:.9;text-transform:uppercase}&:hover{transform:translate(-4px,-4px) rotate(${p=>p.$blue?1:-1}deg);box-shadow:${p=>p.theme.shadows.strong}}&:active{transform:none;box-shadow:${p=>p.theme.shadows.subtle}}`
const State=styled.div`max-width:680px;margin:70px auto 0;padding:clamp(30px,6vw,58px);background:${p=>p.theme.colors.surface};border:3px solid ${p=>p.theme.colors.borderStrong};box-shadow:${p=>p.theme.shadows.strong};transform:rotate(-.5deg);h2{margin:18px 0 10px;text-transform:uppercase}p{color:${p=>p.theme.colors.text.secondary}}`
const Loading=styled.div`display:grid;grid-template-columns:repeat(6,1fr);gap:5px;margin-top:28px;span{height:20px;background:${p=>p.theme.colors.secondary};border:2px solid ${p=>p.theme.colors.borderStrong};animation:punch 900ms ease-in-out infinite alternate}span:nth-child(2){animation-delay:100ms}span:nth-child(3){animation-delay:200ms}span:nth-child(4){animation-delay:300ms}span:nth-child(5){animation-delay:400ms}span:nth-child(6){animation-delay:500ms}@keyframes punch{to{transform:translateY(-8px);background:${p=>p.theme.colors.primary}}`

const Dashboard=()=>{const navigate=useNavigate();const{habits,toggleYesNoCompletion,isLoading,hasLoaded,error}=useHabits();const{weekStartsOn}=usePreferences();const{showSuccessToast,showErrorToast}=useToast();const[todayHabits,setTodayHabits]=useState([]);const[weeklyData,setWeeklyData]=useState([]);const[stats,setStats]=useState({});const[showConfetti,setShowConfetti]=useState(false)
useEffect(()=>{setTodayHabits(getTodayHabits(habits));setWeeklyData(getWeeklyCompletionData(habits,new Date(),weekStartsOn));setStats(getTrackingStats(habits))},[habits,weekStartsOn])
const rate=stats.completionRate||0,completed=stats.todayCompletions||0,total=stats.totalHabits||0,streak=stats.maxStreak||0
const toggle=async id=>{const habit=todayHabits.find(h=>h.id===id);if(!habit)return{ok:false};const completing=!habit.isCompleted;const result=await toggleYesNoCompletion(id);if(!result.ok){showErrorToast(`Ticket failed: "${habit.name}". Give it another go.`);return result}const updated=todayHabits.map(h=>h.id===id?{...result.habit,isCompleted:isCompletedOnDate(result.habit,toDateKey())}:h);if(completing){showSuccessToast(`Ticket punched: "${habit.name}".`);const count=updated.filter(h=>h.isCompleted).length;if(count===total&&total>0){setShowConfetti(true);showSuccessToast('Full house! Every habit is complete.')}else if(count%3===0)setShowConfetti(true)}return result}
const cheer=rate===100?{title:'Full house!',text:'Every ticket is punched. Today officially counts.'}:rate>=75?{title:'Nearly there!',text:'One more small promise and this page is complete.'}:streak>=7?{title:'That’s a proper streak.',text:`Your best habit has shown up for ${streak} days.`}:{title:'First punch wins.',text:'Pick the ticket that feels easiest and make some satisfying progress.'}
const header=<><h1 className="sr-only">Dashboard</h1><Header><Logo>Sunday Club</Logo><DateStamp>{format(new Date(),'EEE / dd MMM').toUpperCase()} · issue {getDayOfYear(new Date())}</DateStamp></Header></>
if(isLoading&&!hasLoaded)return<Shell aria-busy="true">{header}<State><AppIcon name="activity" size={38}/><h2>Printing today’s tickets</h2><p>Your private habit record is getting the fresh-paper treatment.</p><Loading>{Array.from({length:6},(_,i)=><span key={i}/>)}</Loading><span className="sr-only">Loading habits</span></State></Shell>
if(error)return<Shell>{header}<State role="alert"><AppIcon name="circle-x" size={38}/><h2>Ticket machine snoozing</h2><p>Your completions are safe. Give the local service another nudge.</p><Button onClick={()=>window.location.reload()}>Nudge it</Button></State></Shell>
if(habits.length===0)return<Shell>{header}<EmptyState type="habits" title="Your first ticket is blank" description="Write one recurring promise you would actually enjoy keeping, then punch it when it happens." actionText="Make a ticket" onAction={()=>navigate('/add-habit')}/></Shell>
return<Shell initial={{opacity:0}} animate={{opacity:1}}><Confetti run={showConfetti} onComplete={()=>setShowConfetti(false)}/>{header}<Hero><HeroCopy><Badge>Five tiny promises</Badge><h1>Make today count.</h1><p>Habits should feel satisfying, not solemn. Tear them off as you go and keep the story moving.</p></HeroCopy><Score><span>Today’s score</span><strong>{completed} / {total}</strong><span>{rate}% of tickets punched</span><Sticker>{rate===100?'YES!':'NICE!'}</Sticker></Score></Hero>
<Week aria-label="Seven days of completions"><WeekTitle>This week’s punch card</WeekTitle>{weeklyData.map(day=><Day key={day.date} $today={day.isToday} $complete={day.completed>0} title={`${day.day}: ${day.completed} completions`}><span>{day.day.slice(0,2)}</span><strong>{day.completed}</strong><i/></Day>)}</Week>
<Bulletin><Pin>!</Pin><div><h2>{cheer.title}</h2><p>{cheer.text}</p></div><Button className="bulletin-action" variant="ghost" onClick={()=>navigate('/progress')}>See the score</Button></Bulletin>
<Section aria-labelledby="tickets-title"><SectionHeader><div><Kicker>Today’s tear-offs</Kicker><h2 id="tickets-title">Punch your promises</h2></div><Button variant="ghost" icon="plus" onClick={()=>navigate('/add-habit')}>Add Habit</Button></SectionHeader><Tickets>{todayHabits.map((habit,index)=>{const live=habits.find(h=>h.id===habit.id)||habit,active=Boolean(habit.isCompleted),count=live.type==='count';return<Ticket key={habit.id} $tilt={index%3===0?-1:index%3===1?1:0} onClick={()=>navigate(`/habit/${habit.id}`)} initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{duration:.4,delay:index*.05}}><TicketCopy><h3>{habit.name}</h3><TicketMeta><Icon $color={habit.color}><AppIcon name={habit.icon} fallbackName={DEFAULT_HABIT_ICON} size={18}/></Icon><span>{getHabitStreak(live)} day streak</span><span>·</span><span>{active?'Done today':'Ready to punch'}</span></TicketMeta></TicketCopy>{count?<CountTear onClick={e=>e.stopPropagation()}><CountStepper habit={live}/></CountTear>:<Tear type="button" $active={active} aria-label={`${active?'Mark as incomplete':'Mark as complete'}: ${habit.name}`} onClick={e=>{e.stopPropagation();toggle(habit.id)}}><AppIcon name={active?'check':'ticket'} fallbackName="check" size={22}/><span>{active?'Done':'Tear'}</span></Tear>}</Ticket>})}</Tickets></Section>
<Section aria-labelledby="next-title"><SectionHeader><div><Kicker>Keep the issue</Kicker><h2 id="next-title">The rest of your story</h2></div></SectionHeader><PathGrid><Path type="button" onClick={()=>navigate('/calendar')}><strong>Open the calendar</strong><AppIcon name="calendar" size={32}/></Path><Path type="button" $blue onClick={()=>navigate('/journal')}><strong>Write the next line</strong><AppIcon name="notebook" size={32}/></Path></PathGrid></Section></Shell>}
export default Dashboard
