import React from 'react'
import {
  IconAbacus,
  IconActivity,
  IconAlarm,
  IconApple,
  IconArchive,
  IconAvocado,
  IconBanana,
  IconBallFootball,
  IconBarbell,
  IconBath,
  IconBed,
  IconBell,
  IconBike,
  IconBolt,
  IconBook,
  IconBook2,
  IconBottle,
  IconBowl,
  IconBrain,
  IconBread,
  IconBrush,
  IconBuildingBank,
  IconBulb,
  IconBus,
  IconCalendar,
  IconCalendarWeek,
  IconCamera,
  IconCandle,
  IconCar,
  IconCarrot,
  IconChartBar,
  IconChartHistogram,
  IconChartLine,
  IconCheck,
  IconCheckbox,
  IconChess,
  IconChevronLeft,
  IconChevronRight,
  IconCircleCheck,
  IconCircleX,
  IconClipboardList,
  IconClock,
  IconCode,
  IconCoffee,
  IconCoin,
  IconConfetti,
  IconDental,
  IconDeviceFloppy,
  IconDeviceGamepad2,
  IconDeviceLaptop,
  IconDiamond,
  IconDownload,
  IconDroplet,
  IconEgg,
  IconFileSpreadsheet,
  IconFireExtinguisher,
  IconFlame,
  IconFlower,
  IconFolder,
  IconGift,
  IconGuitarPick,
  IconHeadphones,
  IconHeart,
  IconHeartHandshake,
  IconHome,
  IconInbox,
  IconKey,
  IconKeyboard,
  IconLanguage,
  IconLayoutDashboard,
  IconLeaf,
  IconListCheck,
  IconLock,
  IconMailHeart,
  IconMasksTheater,
  IconMessage,
  IconMessageCircle,
  IconMicrophone,
  IconMicroscope,
  IconMinus,
  IconMilk,
  IconMoon,
  IconMovie,
  IconMusic,
  IconNeedleThread,
  IconNotebook,
  IconNotes,
  IconMoodSmile,
  IconPalette,
  IconPeace,
  IconPencil,
  IconPhone,
  IconPill,
  IconPin,
  IconPlant2,
  IconPlus,
  IconPray,
  IconPuzzle,
  IconRainbow,
  IconReceipt,
  IconRefresh,
  IconRepeat,
  IconRestore,
  IconRocket,
  IconRun,
  IconSalad,
  IconScale,
  IconSearch,
  IconSeedling,
  IconSettings,
  IconShoppingCart,
  IconSoup,
  IconSparkles,
  IconStar,
  IconStars,
  IconStethoscope,
  IconSun,
  IconSwimming,
  IconTarget,
  IconTelescope,
  IconTestPipe,
  IconTools,
  IconToolsKitchen2,
  IconTrophy,
  IconUpload,
  IconUsers,
  IconUsersGroup,
  IconVideo,
  IconWalk,
  IconWashMachine,
  IconWorld,
  IconWriting,
  IconX,
  IconYoga
} from '@tabler/icons-react'
import {
  DEFAULT_HABIT_ICON,
  getLegacyIconText,
  normalizeIconName
} from '../domain/iconCatalog'

const TABLER_ICONS = {
  abacus: IconAbacus,
  activity: IconActivity,
  alarm: IconAlarm,
  apple: IconApple,
  archive: IconArchive,
  avocado: IconAvocado,
  banana: IconBanana,
  bank: IconBuildingBank,
  barbell: IconBarbell,
  bath: IconBath,
  bed: IconBed,
  bell: IconBell,
  bike: IconBike,
  bolt: IconBolt,
  book: IconBook,
  books: IconBook2,
  bottle: IconBottle,
  bowl: IconBowl,
  brain: IconBrain,
  bread: IconBread,
  brush: IconBrush,
  bulb: IconBulb,
  bus: IconBus,
  calendar: IconCalendar,
  'calendar-week': IconCalendarWeek,
  camera: IconCamera,
  candle: IconCandle,
  car: IconCar,
  carrot: IconCarrot,
  'chart-bar': IconChartBar,
  'chart-histogram': IconChartHistogram,
  'chart-line': IconChartLine,
  check: IconCheck,
  checkbox: IconCheckbox,
  chess: IconChess,
  'chevron-left': IconChevronLeft,
  'chevron-right': IconChevronRight,
  'circle-check': IconCircleCheck,
  'circle-x': IconCircleX,
  clean: IconBrush,
  clipboard: IconClipboardList,
  clock: IconClock,
  code: IconCode,
  coffee: IconCoffee,
  coin: IconCoin,
  confetti: IconConfetti,
  cooking: IconToolsKitchen2,
  cup: IconMilk,
  dental: IconDental,
  diamond: IconDiamond,
  download: IconDownload,
  droplet: IconDroplet,
  dumbbell: IconBarbell,
  egg: IconEgg,
  extinguisher: IconFireExtinguisher,
  family: IconUsersGroup,
  'file-spreadsheet': IconFileSpreadsheet,
  flame: IconFlame,
  flower: IconFlower,
  folder: IconFolder,
  fruit: IconApple,
  game: IconBallFootball,
  gamepad: IconDeviceGamepad2,
  gift: IconGift,
  guitar: IconGuitarPick,
  handshake: IconHeartHandshake,
  headphones: IconHeadphones,
  heart: IconHeart,
  home: IconHome,
  inbox: IconInbox,
  key: IconKey,
  keyboard: IconKeyboard,
  language: IconLanguage,
  laptop: IconDeviceLaptop,
  laundry: IconWashMachine,
  leaf: IconLeaf,
  'list-check': IconListCheck,
  lock: IconLock,
  'mail-heart': IconMailHeart,
  meal: IconToolsKitchen2,
  message: IconMessageCircle,
  'message-square': IconMessage,
  microphone: IconMicrophone,
  microscope: IconMicroscope,
  minus: IconMinus,
  moon: IconMoon,
  movie: IconMovie,
  'mood-smile': IconMoodSmile,
  music: IconMusic,
  notebook: IconNotebook,
  notes: IconNotes,
  palette: IconPalette,
  peace: IconPeace,
  pencil: IconPencil,
  phone: IconPhone,
  pill: IconPill,
  pin: IconPin,
  piano: IconMusic,
  plant: IconPlant2,
  plus: IconPlus,
  pray: IconPray,
  progress: IconChartLine,
  puzzle: IconPuzzle,
  rainbow: IconRainbow,
  receipt: IconReceipt,
  refresh: IconRefresh,
  repeat: IconRepeat,
  restore: IconRestore,
  rocket: IconRocket,
  run: IconRun,
  salad: IconSalad,
  scale: IconScale,
  search: IconSearch,
  seedling: IconSeedling,
  settings: IconSettings,
  sewing: IconNeedleThread,
  'shopping-cart': IconShoppingCart,
  star: IconStar,
  sparkles: IconSparkles,
  stethoscope: IconStethoscope,
  sun: IconSun,
  swim: IconSwimming,
  target: IconTarget,
  tea: IconCoffee,
  telescope: IconTelescope,
  'test-tube': IconTestPipe,
  theater: IconMasksTheater,
  thread: IconNeedleThread,
  toothbrush: IconDental,
  tools: IconTools,
  trophy: IconTrophy,
  upload: IconUpload,
  users: IconUsers,
  vegetable: IconCarrot,
  video: IconVideo,
  walk: IconWalk,
  wash: IconBath,
  world: IconWorld,
  writing: IconWriting,
  x: IconX,
  yoga: IconYoga
}

export const hasTablerIcon = icon => Boolean(TABLER_ICONS[normalizeIconName(icon)])

const AppIcon = ({
  name,
  fallbackName = DEFAULT_HABIT_ICON,
  size = 24,
  stroke = 2,
  decorative = true,
  label,
  className,
  style
}) => {
  const normalizedName = normalizeIconName(name)
  const IconComponent = normalizedName
    ? TABLER_ICONS[normalizedName]
    : TABLER_ICONS[fallbackName]

  if (IconComponent) {
    return (
      <IconComponent
        className={className}
        style={style}
        size={size}
        stroke={stroke}
        aria-hidden={decorative ? 'true' : undefined}
        aria-label={decorative ? undefined : label}
        role={decorative ? undefined : 'img'}
        focusable="false"
      />
    )
  }

  const legacyText = getLegacyIconText(name)
  if (!legacyText) return null

  return (
    <span
      className={className}
      style={style}
      aria-hidden={decorative ? 'true' : undefined}
      aria-label={decorative ? undefined : label}
      role={decorative ? undefined : 'img'}
    >
      {legacyText}
    </span>
  )
}

export default AppIcon
