import React from'react'
import{useNavigate}from'react-router-dom'
import styled from'styled-components'
import{motion}from'framer-motion'
import{getDayOfYear}from'date-fns'
import{useNavigation}from'../context/NavigationContext'
import AppIcon from'./AppIcon'

const Nav=styled.nav`position:fixed;right:0;bottom:0;left:0;z-index:100;height:calc(76px + env(safe-area-inset-bottom,0px));display:grid;grid-template-columns:repeat(6,minmax(0,1fr));padding-bottom:env(safe-area-inset-bottom,0px);background:${p=>p.theme.colors.surface};border-top:2px solid ${p=>p.theme.colors.borderStrong};box-shadow:0 -5px 0 ${p=>p.theme.colors.secondary};@media(min-width:${p=>p.theme.breakpoints.tablet}){top:0;right:0;bottom:0;left:auto;width:176px;height:100vh;display:flex;flex-direction:column;padding:0;border-top:0;border-left:2px solid ${p=>p.theme.colors.borderStrong};box-shadow:-7px 0 0 ${p=>p.theme.colors.secondary}}`
const Brand=styled.button`display:none;@media(min-width:${p=>p.theme.breakpoints.tablet}){height:176px;display:flex;flex-direction:column;justify-content:space-between;padding:18px 16px;background:${p=>p.theme.colors.borderStrong};color:${p=>p.theme.colors.background};text-align:left;transform-origin:top right;&:hover{background:${p=>p.theme.colors.primary};color:${p=>p.theme.colors.onPrimary}}}`
const BrandTop=styled.span`font-family:${p=>p.theme.typography.monoFamily};font-size:.58rem;letter-spacing:.1em;text-transform:uppercase`
const BrandName=styled.strong`font-family:${p=>p.theme.typography.displayFamily};font-size:1.7rem;font-weight:800;line-height:.82;letter-spacing:-.08em;text-transform:uppercase`
const Item=styled(motion.button)`position:relative;min-width:0;min-height:72px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;padding:6px 2px;background:${p=>p.$active?p.theme.colors.primary:'transparent'};color:${p=>p.$active?p.theme.colors.onPrimary:p.theme.colors.text.primary};border-right:2px solid ${p=>p.theme.colors.borderStrong};transition:background var(--duration-fast),color var(--duration-fast),transform var(--duration-fast);&:last-of-type{border-right:0}&::after{content:'';position:absolute;top:0;right:0;left:0;height:7px;background:${p=>p.theme.colors.secondary};transform:scaleX(${p=>p.$active?1:0});transition:transform var(--duration-base) var(--ease-spring)}&:hover:not(:disabled){background:${p=>p.$active?p.theme.colors.primaryHover:p.theme.colors.secondary};color:${p=>p.$active?p.theme.colors.onPrimary:p.theme.colors.ink}}&:active:not(:disabled){transform:translateY(3px)}@media(min-width:${p=>p.theme.breakpoints.tablet}){width:100%;min-height:66px;display:grid;grid-template-columns:22px minmax(0,1fr);justify-items:start;gap:9px;padding:10px 14px;border-right:0;border-bottom:2px solid ${p=>p.theme.colors.borderStrong};&::after{top:0;right:auto;bottom:0;left:0;width:7px;height:auto;transform:scaleY(${p=>p.$active?1:0})}&:active:not(:disabled){transform:translateX(-3px)}}`
const Label=styled.span`max-width:100%;overflow:hidden;font-size:clamp(.46rem,2.3vw,.62rem);font-weight:700;line-height:1;text-overflow:ellipsis;text-transform:uppercase;white-space:nowrap;@media(min-width:${p=>p.theme.breakpoints.tablet}){font-size:.66rem}`
const Footer=styled.div`display:none;@media(min-width:${p=>p.theme.breakpoints.tablet}){margin-top:auto;display:block;padding:15px;border-top:2px solid ${p=>p.theme.colors.borderStrong};font-family:${p=>p.theme.typography.monoFamily};font-size:.55rem;line-height:1.45;text-transform:uppercase}`
const items=[{id:'dashboard',label:'Today!',icon:'confetti',path:'/'},{id:'habits',label:'Habits',icon:'checkbox',path:'/habits'},{id:'calendar',label:'Calendar',icon:'calendar',path:'/calendar'},{id:'journal',label:'Story',icon:'notebook',path:'/journal'},{id:'progress',label:'Score',icon:'trophy',path:'/progress'},{id:'settings',label:'Me',icon:'settings',path:'/settings'}]
const BottomNavigation=()=>{const navigate=useNavigate();const{activeTab,setActiveTab}=useNavigation();const go=item=>{setActiveTab(item.id);navigate(item.path)};return<Nav aria-label="Primary navigation"><Brand type="button" onClick={()=>go(items[0])} aria-label="Go to today"><BrandTop>Issue no. {getDayOfYear(new Date())}</BrandTop><BrandName>Sunday<br/>Club</BrandName></Brand>{items.map(item=><Item key={item.id} type="button" $active={activeTab===item.id} onClick={()=>go(item)} aria-label={item.label} aria-current={activeTab===item.id?'page':undefined}><AppIcon name={item.icon} size={20}/><Label>{item.label}</Label></Item>)}<Footer>Five tiny promises.<br/>Punch them as you go.</Footer></Nav>}
export default BottomNavigation
